#!/usr/bin/env python3

'''gsrename: rename Gradescope submissions

Usage:
    gsrename [options] <file>

Options:
    <FILE>                      downloaded zip file or metadata YAML file
    -o <dir>, --output <dir>    output directory [default: .]
'''

import docopt
import metadata
import os
import shutil


args = docopt.docopt(__doc__)
data, get_file = metadata.load_metadata(args['<file>'])

copies = []

for (filename, metadata) in data.items():
    extension = os.path.splitext(filename)[-1]

    for s in metadata[':submitters']:
        new_name = f'{s[":sid"]} - {s[":name"]}{extension}'
        copies.append((filename, new_name))

# Create output directory
try:
    os.mkdir(args['--output'])
except FileExistsError:
    pass

for (source, dest) in copies:
    dest = os.path.join(args['--output'], dest)

    print(f'{source} -> {dest}')
    shutil.copyfileobj(get_file(source), open(dest, 'wb'))
