#!/usr/bin/env python3

'''gsrename: rename Gradescope submissions

Usage:
    gsrename [options] <METADATA_FILE>

Options:
    -o <dir>, --output <dir>    output directory [default: .]
'''

import docopt
import os
import shutil
import yaml

args = docopt.docopt(__doc__)

f = open(args['<METADATA_FILE>'], 'r')
data = yaml.load(f)

copies = []

for (filename, metadata) in data.items():
    extension = os.path.splitext(filename)[-1]

    for s in metadata[':submitters']:
        new_name = f'{s[":sid"]} - {s[":name"]}.{extension}'
        copies.append((filename, new_name))

try:
    os.mkdir(args['--output'])
except FileExistsError:
    pass

for (old, new) in copies:
    new = f'{args["--output"]}/{new}'
    print(f'{old} -> {new}')

    shutil.copyfile(old, new)
